[tool.poetry]
name = "rag-api"
version = "0.1.0"
description = ""
authors = ["nkap360 <39144511+nkap360@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
